### ISSUE TITLE
Installer broke the game, cannot repair

### ISSUE THREAD

**Issue by artemonster** [MartinSGill/SubnauticaWatcher#17]
The installer said something about Assembly-CSharp.dll having a virus.
In the log file of the install I found a stack trace when backing up Assembly-CSharp.dll, and after that I cannot repair the game files. Tried removing installing again - steam cannot reinstall the game. WTF?

**Comment by MartinSGill** [comment]
The installer is very unlikely to break the game, and certainly not to insert a virus. Feel free to read the code yourself to verify my assertion.

The only file the installer modifies is Assembly-CSharp.dll. You can either restore that file from the backup, or simply delete it and have steam validate the game files so that it's re-downloaded. If that doesn't work, then delete your entire subnautica folder and have steam reacquire it.

If the game fails to re-install/validate then please contact Steam support.
