### ISSUE TITLE
have you thought about actually including the .exe instead of the .csproj

### ISSUE THREAD

**Issue by martinsgillretarded** [MartinSGill/SubnauticaWatcher#21]
seems very simple
especially if you're going to build both your 'walkthroughs' on using your program around using the .exe
lmao

**Comment by MartinSGill** [comment]
Offensive names are not required.

I also have no idea what you are talking about. I don't provide a walkthrough. All I provide is a map mod, and I recommend not using the mod until you've played the game once for yourself, to get the full exploration experience.

If you go to the releases page, that's where the installer and the exe's are, as is expected. The main page is the source code, which is of the point of github.

If someone else is linking you to the source code, instead of the release, then you need to take that up with them.
